version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - node
    links:
      - node

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker

  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=docker
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker

  redis:
    container_name: redis
    image: redis:5
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./backend:/home/app
      - /home/app/node_modules
      - /home/app/build
    command: yarn dev
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  postgres-data:
  mysql-data:
  mongo-data:
  redis-data: